image: node:16-alpine
cache: &global_cache
  key:
    files:
      - yarn.lock
  paths:
    - .yarn-cache/

stages:
  - build

build:
  stage: build
  before_script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache --prefer-offline
  script:
    - yarn test --ci --reporters=default --reporters=jest-junit
    - yarn build
  artifacts:
    paths:
      - packages/**/dist/
    expire_in: 1 week
    reports:
      junit: junit.xml
