image: node:16-alpine

stages:
  - build

build:
  stage: build
  before_script:
    - yarn install --frozen-lockfile --cache-folder .yarn
  script:
    - yarn build
  artifacts:
    paths:
      - packages/**/dist/
    expire_in: 1 week
