image: node:16-alpine

stages:
  - install-dependencies

cache: &global_cache
  key:
    files:
      - yarn.lock
  paths:
    - .npm/
  policy: pull

install-dependencies:
  stage: install-dependencies
  script: npm ci --cache .npm --prefer-offline
  cache:
    - <<: *global_cache
      policy: push
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - changes:
        - yarn.lock
