image: node:16-alpine

stages:
  - build

build:
  stage: build
  before_script:
    - ln -sf documents examples/nextjs/public/documents
    - npm install --cache .npm --prefer-offline
  script:
    - npm run build
  artifacts:
    paths:
      - packages/**/dist/
    expire_in: 1 week
