/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=code/web/wrangler.writing-test.jsonc --env-file=/dev/null --include-runtime=false --strict-vars=false code/web/src/cloudflare-bindings.d.ts` (hash: dbe1ae74fd5467f72000d1cc4495f0d0)
interface __BaseEnv_Env {
	WRITING_MEDIA: R2Bucket;
	ASSETS: Fetcher;
	WRITING_REPO_OWNER: string;
	WRITING_REPO_NAME: string;
	WRITING_AUTHOR_NAME: string;
	WRITING_AUTHOR_EMAIL: string;
	WRITING_R2_BUCKET: string;
	WRITING_SELF: Service<typeof import("./worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WRITING_REPO_OWNER" | "WRITING_REPO_NAME" | "WRITING_AUTHOR_NAME" | "WRITING_AUTHOR_EMAIL" | "WRITING_R2_BUCKET">> {}
}
