/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=code/web/wrangler.writing-test.jsonc --include-runtime=false --env-interface=HostedWritingBindings code/web/src/writing-test-bindings.d.ts` (hash: c9ca05e2bb847519f28e28f9c5d91162)
interface __BaseEnv_HostedWritingBindings {
	SESSIONS: KVNamespace;
	WRITING_MEDIA: R2Bucket;
	WRITING_AUTH_DB: D1Database;
	ASSETS: Fetcher;
	WRITING_REPO_OWNER: "ncrmro";
	WRITING_REPO_NAME: "quiescent-writing-demo";
	WRITING_AUTHOR_NAME: "Nicholas Romero";
	WRITING_AUTHOR_EMAIL: "ncrmro@users.noreply.github.com";
	WRITING_R2_BUCKET: "quiescent-writing-demo-images";
	WRITING_TEST: "true";
	BETTER_AUTH_URL: "https://quiescent-writing-test.ncrmro.workers.dev";
	DEV_PORT: string;
	DEV_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../dist/_worker.js/index");
	}
	interface Env extends __BaseEnv_HostedWritingBindings {}
}
interface HostedWritingBindings extends __BaseEnv_HostedWritingBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WRITING_REPO_OWNER" | "WRITING_REPO_NAME" | "WRITING_AUTHOR_NAME" | "WRITING_AUTHOR_EMAIL" | "WRITING_R2_BUCKET" | "WRITING_TEST" | "BETTER_AUTH_URL" | "DEV_PORT" | "DEV_URL">> {}
}
