/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=code/web/wrangler.writing-test.jsonc --include-runtime=false --env-interface=HostedWritingBindings code/web/src/writing-test-bindings.d.ts` (hash: ef0db13b54913413d191f7c243b2f705)
interface __BaseEnv_HostedWritingBindings {
	WRITING_MEDIA: R2Bucket;
	ASSETS: Fetcher;
	WRITING_REPO_OWNER: "ncrmro";
	WRITING_REPO_NAME: "quiescent-writing-demo";
	WRITING_AUTHOR_NAME: "Nicholas Romero";
	WRITING_AUTHOR_EMAIL: "ncrmro@users.noreply.github.com";
	WRITING_R2_BUCKET: "quiescent-writing-demo-images";
	WRITING_TEST: "true";
	DEV_PORT: string;
	DEV_URL: string;
	WRITING_SELF: Service<typeof import("./worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_HostedWritingBindings {}
}
interface HostedWritingBindings extends __BaseEnv_HostedWritingBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WRITING_REPO_OWNER" | "WRITING_REPO_NAME" | "WRITING_AUTHOR_NAME" | "WRITING_AUTHOR_EMAIL" | "WRITING_R2_BUCKET" | "WRITING_TEST" | "DEV_PORT" | "DEV_URL">> {}
}
