/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.writing.jsonc --include-runtime=false --env-interface=WritingBindings src/writing-bindings.d.ts` (hash: a5b037a0078b3e163ae39be7438992d0)
interface __BaseEnv_WritingBindings {
	SESSIONS: KVNamespace;
	DRAFTS: KVNamespace;
	WRITING_MEDIA: R2Bucket;
	ASSETS: Fetcher;
	WRITING_LOCAL: "true";
	WRITING_REPO_OWNER: "ncrmro";
	WRITING_REPO_NAME: "quiescent-writing-demo";
	WRITING_AUTHOR_NAME: "Nicholas Romero";
	WRITING_AUTHOR_EMAIL: "ncrmro@users.noreply.github.com";
	WRITING_R2_BUCKET: "quiescent-writing-demo-images";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../dist/_worker.js/index");
	}
	interface Env extends __BaseEnv_WritingBindings {}
}
interface WritingBindings extends __BaseEnv_WritingBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WRITING_LOCAL" | "WRITING_REPO_OWNER" | "WRITING_REPO_NAME" | "WRITING_AUTHOR_NAME" | "WRITING_AUTHOR_EMAIL" | "WRITING_R2_BUCKET">> {}
}
