/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=code/web/wrangler.writing.jsonc --include-runtime=false --env-interface=WritingBindings code/web/src/writing-bindings.d.ts` (hash: 99cfbc0d1afdc6d38db128b7b8375527)
interface __BaseEnv_WritingBindings {
	WRITING_MEDIA: R2Bucket;
	ASSETS: Fetcher;
	WRITING_LOCAL: "true";
	WRITING_REPO_OWNER: "ncrmro";
	WRITING_REPO_NAME: "quiescent-writing-demo";
	WRITING_AUTHOR_NAME: "Nicholas Romero";
	WRITING_AUTHOR_EMAIL: "ncrmro@users.noreply.github.com";
	WRITING_R2_BUCKET: "quiescent-writing-demo-images";
	DEV_PORT: string;
	DEV_URL: string;
	WRITING_SELF: Service<typeof import("./worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_WritingBindings {}
}
interface WritingBindings extends __BaseEnv_WritingBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WRITING_LOCAL" | "WRITING_REPO_OWNER" | "WRITING_REPO_NAME" | "WRITING_AUTHOR_NAME" | "WRITING_AUTHOR_EMAIL" | "WRITING_R2_BUCKET" | "DEV_PORT" | "DEV_URL">> {}
}
